export { default as Home } from './Home'
export { default as List } from './List'
export { default as Hot } from './Hot'
export { default as Search } from './Search'
export { default as Detail } from './Detail'
export { default as Film } from './Film'
